### ISSUE TITLE
Podverse -  load an enclosure url feature

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#102]
related to #93
Also feel free to edit title to be more accurate.

Tracking and discussion of [mitchdowney](https://github.com/mitchdowney)'s collaborations on the Podverse embedded player for our specific feature request to enable local files to be loaded into the Podverse player, as opposed to from the Podverse directory.

...which is amazing! Thanks Podverse!

Relevant conversation snippets:

**Comment by gerbrent** [comment]
@kbondarev wrote:

As far as I understand, the way to use the player right now is to embed it using an iframe with a src that has a [podverse.fm](http://podverse.fm/) link that include a unique ID to the episode (e.g. https://podverse.fm/embed/player?episodeId=kilYJsW3A)

That would mean that the episode has already been published into the RSS feed and picked up by podverse. However, as I understand it, the goal for the new site is to be the "source-of-truth", it would be generating RSS from Hugo markdown files (at least that's how I understand the process now). So the iframe of the player has two challenges:

* RSS feed has to be already generated before the episode page on the site could have a the embedded player to it
* How do we find that episdoeid?

One way how I see it all solved would be if we could use the Podverse embedded player as a JS library, that would allow passing data to each instance of the player about the episode it needs to play.
It could be maybe maybe be a URL/string data of the whole RSS feed of the show and a GUID of the episode that should be played.

**Comment by gerbrent** [comment]
@mitchdowney wrote:

1. Create the JP page for the episode.

2. Paste the Podverse embed code, and pass in URL param overrides for podcast title, enclosure url, episode title, episode pub date, and possibly an episode GUID, so it can render with that information immediately.

2b) We would need to disable the on-click "open episode in Podverse" behaviors while the embed is using the overridden method. Chapters and the lightning icon would also be missing.

3. Publish the JP episode page.

4. When a visitor lands on the page, the embed will first check if an episode with that enclosure url (or episode GUID) already exists in our database. If no, then the embed renders with the override params. If yes, then it ignores the override params, and loads the full parsed data we have from the RSS feed.

**Comment by gerbrent** [comment]
@mitchdowny went away for 4+hrs / a long night, then shared:

this turned into a much bigger feature to think about than I expected when I realized if we let anyone pass in episode info overrides to the player, then anyone could load whatever they want through [podverse.fm](http://podverse.fm/), including premium/private feeds or pirate feeds 😳

To work around this, I added an embedApprovedMediaUrlPaths to our Podcast table. For Linux Unplugged in our database, I set embedApprovedMediaUrlPaths to "https://aphid.fireside.fm/d/1437767933/". If you try to load an enclosure url in the embed player that doesn't start with that path, it will fail (horribly).

podcastId and episodeMediaUrl are required.
episodeGuid, episodePubDate, and episodeTile are recommended.

Sample iframe url:
https://podverse.fm/embed/player?podcastId=g40Um-HP1&episodeGuid=92ab2f36-1fef-4cbc-8cec-87b245161c1e&episodeMediaUrl=https://aphid.fireside.fm/d/1437767933/f31a453c-fa15-491f-8618-3f71f1d565e5/92ab2f36-1fef-4cbc-8cec-87b245161c1e.mp3&episodeTitle=custom%20title&episodePubDate=800000000

Code changes:
https://github.com/podverse/podverse-api/pull/493/files
https://github.com/podverse/podverse-web/pull/832/files

Alllright, hopefully that works! If anyone has a chance to try it out and get back to me I'd appreciate it. I'll be mostly unavailable to code tomorrow and possibly Wednesday, but by the weekend I could make changes / fixes as needed.

**Comment by gerbrent** [comment]
So.... we need feedback! Lets give this a try and provide feedback for Mitch.

**Comment by kbondarev** [comment]
I will have some free time later today and I’ll try to set it up.

**Comment by kbondarev** [comment]
(oops :fearful:  I originally posted this in the wrong issue )

@mitchdowney, I appreciate a lot your quick fix and I appologize for the late feedback. It's been a busy week.

I implmented everything as you describe it and it works :smile: :fire: 
However, there are a few rough edges/pain points:

1) The player ends up rendering in the  ["show-all-episodes" mode](https://podverse.fm/embed/player?podcastId=g40Um-HP1&episodeGuid=92ab2f36-1fef-4cbc-8cec-87b245161c1e&episodeMediaUrl=https://aphid.fireside.fm/d/1437767933/f31a453c-fa15-491f-8618-3f71f1d565e5/92ab2f36-1fef-4cbc-8cec-87b245161c1e.mp3&episodeTitle=custom%20title&episodePubDate=800000000) rather than the ["only-one-episode" mode](https://podverse.fm/embed/player?episodeId=kilYJsW3A) which is produced when give only the `episodeId`.

This not ideal, but also not a big issue since the iframe hides it:

<kbd>![image](https://user-images.githubusercontent.com/7744333/179157434-bf5efdef-f511-4721-82f9-58676b441e2b.png)</kbd>

However, the "show-all-episodes" mode doesn't hide the "full-screen" button at the top-right corner of the player. It becomes a mess if you click it, since it's inside the iframe:

<kbd>![image](https://user-images.githubusercontent.com/7744333/179157886-724677d2-e752-4606-93cd-20d86882240a.png)</kbd>


Is it possible to send more events to the parent like [here](https://github.com/podverse/podverse-web/blob/develop/pages/embed/player.tsx#L59).
For example, when the `full-screen` mode is toggled on/off. I could maybe then change the style of the `<iframe>` itself and make it also cover the whole screen. It might be a neat hack around it :)
Then we would not lose those extra control buttons in the full-screen mode.
I don't know how the other events for user actions might become handy, but I don't see any reason why not send them :). For example, clicked-play, clicked-pause, clicked-next-chapter, etc.



I looked into the code a little, and found the `showAllEpisodes` boolean URL param that I could pass, but it didn't have an effect.


2) I also wanted to change the style of the player to match better the theme on the site. I looked at [this example](https://podverse.fm/embed/player-demo-custom-css) and [the code](https://github.com/podverse/podverse-web/blob/develop/pages/embed/player-demo-custom-css.tsx) and implemented something similar. But it results in a CORS error:

```
Uncaught DOMException: Blocked a frame with origin "http://localhost:1313" from accessing a cross-origin frame.
    at pvSetCSSVariable (http://localhost:1313/show/linux-unplugged/466/:423:41)
    at pvHandleCSSOverrides (http://localhost:1313/show/linux-unplugged/466/:426:13)
```

Maybe the way to do this is to pass the CSS as URL query params as well?

**Comment by kbondarev** [comment]
Also I guess the rest of the shows would need the same permissions. Here are the Podverse IDs: 

- ~linux-unplugged `g40Um-HP1` (done)~ 
- coder-radio: `ZXd_1Ojd9`
- jupiter-extras: `0vaTwihG1R`
- linux-action-news: `haAiVbD1N9`
- office-hours: `GLuztlxs0`
- self-hosted: `nUl1ZCL76`

**Comment by mitchdowney** [comment]
@kbondarev sorry about the full-view bug in the episode only player. I just deployed a fix that should hopefully fix it for you. Now the full-view button should _only_ appear when the `showAllEpisodes=true` param is passed.

If you need more custom events passed from the iframe, we can do that, although it sounds like it would have just been for a workaround in this case. We should fix the root issue in this case. As for other events...if there are iframe events you'd like added, can you please create an issue in https://github.com/podverse/podverse-web with the list of events you'd like?

As for the custom styles embed CORS issue...dang. I didn't try it with a different domain 🤦‍♂️ I wonder if that can be fixed by changing the CORS settings returned from our SSR server? Do you know for sure if the CORS issue is coming from podverse.fm, or is it something specific to your localhost setup? Sorry I'm not great with CORS solutions so I'm not sure what the solution should be...

As for passing in custom styles as URL params...I was really hoping to avoid it since there are so many customizable parameters. Seeing as URLs are limited to 2048 characters, I'm concerned about going that direction. If you have alternate solutions you can imagine, I'd appreciate any ideas.

**Comment by kbondarev** [comment]
I didn't know about he URL limit, you learn something new everyday :))

Regards to CORS it's basically the browser clients that block it based on headers returned by the server. There's away to tell the browser to trust requests coming from different domain than the server by setting up this header:

```
'Access-Control-Allow-Origin', '*'
```

Here's some more info on it specific to Next.js: https://vercel.com/support/articles/how-to-enable-cors#enabling-cors-in-a-next.js-app
I'm not sure if it works the same for iframes, but I don't think it should be different.


Regarding the events. I will think about it more and maybe make some PRs for podverse-web repo on Sunday.

**Comment by StefanS-O** [comment]
So the changes on our end are merged and deployed, for Linux unplugged it is working, all other shows are broken at the moment.

**Comment by kbondarev** [comment]
There was an issue with the approved list of URL on the Podverse side.
@mitchdowney set it all up and now it works for all the shows.
