### ISSUE TITLE
Podverse + Fireside players - low quality audio?

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#141]
While playing a LUP episode via Podverse embedded player via [Episode 465](https://jupiterbroadcasting.net/show/linux-unplugged/465/), the audio has many low-quality compression artifacts. See timestamp 7:16-7:40 for several artifact examples.

artifacts seem to follow conversational pauses/silence.

The questions to find the culprit:
* Where does Podverse pull the episode?
* If a local file (as discussed elsewhere), why are we serving low quality?
* If a remote file, why are they serving low quality?
* If a remote file, why not a local file?
* Etc...

Put your headphones on!

**Comment by elreydetoda** [comment]
So, it's pulling the media from here:
https://media.fireside.fm/file/fireside-audio/podcasts/audio/f/f31a453c-fa15-491f-8618-3f71f1d565e5/episodes/c/c9010224-e034-4b0e-8e86-92bdad797319/c9010224-e034-4b0e-8e86-92bdad797319.mp3

which is the same audio file from fireside... :thinking: 
https://media.fireside.fm/file/fireside-audio/podcasts/audio/f/f31a453c-fa15-491f-8618-3f71f1d565e5/episodes/c/c9010224-e034-4b0e-8e86-92bdad797319/c9010224-e034-4b0e-8e86-92bdad797319.mp3

I don't personally hear any difference but I also don't have the best headphones, so I'm not a judge for that :sweat_smile: 

for the questions:
* (answered with link above)
* it's remote, but we'd talked about for the MVP to have fireside be the source of truth (IIRC) for now with regards to RSS + media (maybe the media was just assumed by me because of the RSS)
* It appears it's the same one that fireside is serving, but I don't know how to control that on their backend (if you can)
* We're not doing local because of a few things (at least in my opinion)
  1. It'd be a LOT of storage on the server after a while (since each podcast will only increase in size)
  2. serving from an S3 target would probably be the most cost effective (when we're doing everything sourced from the website) + there's a lot of redundancy normally with S3 offerings
  3. serving from an s3 endpoint will probably be faster than serving from the server, but just need to make sure we add the right headers on the endpoint to ensure it's getting cached as best as possible (need to implement CDN still, if we do what I've suggested in #16 we'll have a CDN by default (which'll just serve things even faster!))

**Comment by gerbrent** [comment]
Confirming that this is a problem on Fireside aswell, so not related to Podverse.

See here on Fireside: https://linuxunplugged.com/465?t=430

**Comment by drewofdoom** [comment]
Hey, y'all. Quick update on this. Just had a listen to the sample and went back to the original FLACs to check it out. This episode is a bit older, so I don't still have the source files and my project from Studio One - I usually only keep 1-2 older projects at a time.

I do hear some MP3 artifacting, but that's pretty normal. Not going to get rid of that all the way. Such is life with a lossy format.

What I hear is gating. The early consonants are getting picked up too late. I've spoken to the team about adjustments that I want in the gate parameters at the studio during recording times.

I think we can probably close this, as it's not a technical issue with the website or the player, but farther up the chain in the recording/mixing process.
