### ISSUE TITLE
People menu item - links to current page

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#146]
Behavior of the `People` menu item is to link to the current page. 

#### Current behavior: 
* links to the current page. 

#### Desired behavior: 
* link nowhere? Thoughts?

![people menu - wrong link](https://user-images.githubusercontent.com/7018928/180287250-3b20bf62-2a3d-4478-be73-583f68c6c504.gif)

**Comment by reclaimingmytime** [comment]
I think the behavior should be consistent with the other drop-down menus, currently "shows" and "community". These lead to an overview page with an appropriate image and a description, such as for the shows: https://jupiterbroadcasting.net/show/

But I'm not sure if such an overview makes sense for hosts and guests, since both are self-explanatory?

**Comment by gerbrent** [comment]
They sure are self-explanatory.

I wonder if a solution might be to not have `People` be a link at all? That's likely more complex that necessary... this current behaviour is totally... acceptable. Just odd.

**Comment by elreydetoda** [comment]
This was actually closed by #261 : https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/261/commits/27711a3416a9c2cab50db0314a8ea287c19f217f

**Comment by gerbrent** [comment]
amazing! I didn't even notice.... thanks!

**Comment by elreydetoda** [comment]
No problem 😁
It was actually @kbondarev who suggested it during my PR ([here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/252#issuecomment-1210167834) and now that things are pages instead of json files it was pretty easy 😁

**Comment by gerbrent** [comment]
.... go team! 🎉
