### ISSUE TITLE
Memberships page - content reorganization

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#148]
Would someone be willing to do some simple content editing?
Likely a great first issue for someone looking to get involved.

* [x] move the " Network Membership". "Show Memberships" and "Gift Memberships" sections to be ABOVE the "Special Features" list.
* [x] remove the internal links to the shows - the blue/link colour is distracting....... or, perhaps it might look fine? Opinions?

Reasons:
If I came to the page here after hearing about the memberships in one of the shows, I might want to jump to the *Buy Now!* process. If I would like to read more about the implications, it's logical to have that follow..... Further down (the rabbit hole) = more explanation.

**Comment by CGBassPlayer** [comment]
Hi @gerbrent. I can work on this to dip my toe into contributing to my podcast network of choice (love all the shows, been listening since sometime in 2020)


> remove the internal links to the shows - the blue/link colour is distracting......

I agree that the blue links feels distracting. But I wonder if instead of removing the internal links, could we update the CSS to make links similar to the footer? I haven't looked through too much of the new site yet to see how the blue links feel on the other pages, but throwing an idea out there! What are your thoughts?

**Comment by gerbrent** [comment]
love the idea!

If you're willing, you could open a new issue and propose your site-wide change to the link colour if that feels the direction to head, which... I fully support.

**Comment by CGBassPlayer** [comment]
Sure thing. I'll open an issue for the links and put in a pull request for the reorganized membership page

**Comment by CGBassPlayer** [comment]
This issue can be closed. The second task was completed with #199
