### ISSUE TITLE
IPv6 compatibility - jupiterbroadcasting.com does not have IPv6 compatibility

### ISSUE THREAD

**Issue by TeamLinux01** [JupiterBroadcasting/jupiterbroadcasting.com#16]
It seems that there are no AAAA name records for IPv6. Please serve the website on IPv6 as well as IPv4.

https://dnschecker.org/ipv6-compatibility-checker.php was used to quickly check compatibility.

**Comment by elreydetoda** [comment]
To help fix this, since JB already [uses cloudflare for their DNS](https://mxtoolbox.com/SuperTool.aspx?action=whois%3ajupiterbroadcasting.com&run=toolpage), maybe it should be considered to use more features of Cloudflare (i.e. their [IPv6 compatibility gateway](https://www.cloudflare.com/ipv6/)).  This'll help with the IPv6 issue (for both .net + .com) and not require any extra work on the backend server side.

I see that the .com's IP address points directly to [ScaleEngine's IP address](https://whois.domaintools.com/216.66.43.105), so it seems like they might be grey-clouding the JB website instead of proxying then DNS requests ([src](https://developers.cloudflare.com/dns/manage-dns-records/reference/proxied-dns-records/)). If JB was to proxy their DNS requests (orange-cloud), then they'll also get IP address masking (which helps protect the origin from mean people) as well as built-in DDoS protection.

**Comment by TeamLinux01** [comment]
I just want to see more things that use IPv6 so that one day we can get away from IPv4. As long as it doesn't get forgotten about, I can wait. 😁

**Comment by elreydetoda** [comment]
Ya, I completely understand @TeamLinux01, and it was a good suggestion for milestone 1.0 😁

My proposed solution wouldn't require really any work from a server hosting side, and we'd be taking care of our IPv6 breathers 😅

One important reason to ensure that it's compatible, is that if someone that is only IPv6 tries to navigate to the site now...they wouldn't be able to connect to it (since we don't have an IPv6 endpoint/IP address). So, it's an important request to make sure we reach as many people as we can 😁

**Comment by elreydetoda** [comment]
BTW, once JB.net is moved to dev.JB.com it looks we'll be able to close this issue 😁

**Comment by gerbrent** [comment]
I've been advocating for this one throughout!

**Comment by elreydetoda** [comment]
Thanks @gerbrent :grin: 

I think it's awesome that JB is doing this, because just like Chris says all the time with stuff "If we aren't doing it and we've got a technical audience who will" (summary of course :sweat_smile: )

**Comment by ironicbadger** [comment]
How do our new deployment schemes affect this? `new.jb.com` for example...

**Comment by elreydetoda** [comment]
From my perspective, I don't think this will be accomplished until we get Cloudflare DNS proxying implemented. That'd be the only way we could do the IPv6 Gateway feature and it'll transparently handle IPv6 addresses (like I mentioned above: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/16#issuecomment-1186580524 ).

It was working when the dev.jb.com was created, but we don't have the proxying for the new.jb.com.

I posted this in matrix, would this work?
> Just heard in LUP you all use ansible to control DNS instead of terraform, so would it just be adding [proxied](https://docs.ansible.com/ansible/4/collections/community/general/cloudflare_dns_module.html#parameter-proxied) to [this](https://github.com/JupiterBroadcasting/infra/blob/42d8fa0a749a9804d1ab193933afeecb294f5235/ansible/roles/dns/tasks/main.yaml) file?

The only other alternative would be to deploy the server with IPv6, which I don't feel comfortable recommending, because there is so many security things to think of with that :sweat_smile:

**Comment by elreydetoda** [comment]
This is now working with the new.jb.com domain: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/292#issuecomment-1216701221

But since it wasn't enabled for the main domain jb.com ([source](https://whois.domaintools.com/jupiterbroadcasting.com)), this issue should probably still stay open.

**Comment by elreydetoda** [comment]
Now with this https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/355 & https://github.com/JupiterBroadcasting/infra/pull/5 and validating with the picture below we can now close this issue! :partying_face: 

![image](https://user-images.githubusercontent.com/10230166/187555944-c2234085-732b-41ee-b61c-6d12a81bb8a1.png)

Thanks @TeamLinux01 for submitting this :grin:
