### ISSUE TITLE
Community Page - combine Network and Self-Hosted communication methods

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#212]
The [Community](https://jupiterbroadcasting.net/community/) page features two sections currently - `Network-wide` and `Show-specific` communications methods.

Considering there is only one item in `Show-specific` i.e. the SSH Discord - I feel we can simply combine them and mention Self-Hosted in the Discord's description instead. 

Simpler, more visually appealing, and the Community sub-menu and footer has that behaviour by necessity anyhow.
Would also mean we can get rid of the Subtitles on the Community page also. 🎶 So clean and so fresh, fresh. 🎶

**Comment by elreydetoda** [comment]
alright, #271 should close this and one thing to consider as well is that we can always order the methods of communications. For example if you want to have mumble and element show up first we can add [weight](https://gohugo.io/content-management/front-matter/#predefined) to the page and it'll make them first.

That'll probably be a different issue since this was just for combining, but just wanted to mention it :grin:
