### ISSUE TITLE
host/guest profiles - remove Google Plus links

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#265]
The hosts and guests page still links to Google Plus for some hosts and guests, like Joe:
https://jupiterbroadcasting.net/hosts/joe/

The Google Plus link just redirects to the shutdown announcement.

Maybe it's time to remove the link from the template?

**Comment by gerbrent** [comment]
agree!

**Comment by elreydetoda** [comment]
might be a good first issue for someone who's newer and wants to take a little dive into the code :grin: 

Here is where the code is that they'd need to remove:

https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/b716aa253cb6d82990f9f1ee515bf299e8008e16/themes/jb/layouts/partials/people/horizontal.html#L40-L44

It'll remove it for both guests & hosts (which I don't think we have any host that has a google plus link :sweat_smile: )

**Comment by harriseldon** [comment]
I can take this. A good grep on the files and I have a good list. 5 people have a google plus link. Do you want the gplus parameter removed from the json and the follow files changed?
/themes/jb/assets/css/libs/videojs.css
/themes/jb/layouts/partials/hosts/horizontal.html

**Comment by elreydetoda** [comment]
Hey @harriseldon  👋

> good grep on the files and I have a good list

Nice, I didn't even think about doing that 😁 (I'd just thought about the minimum amount of work to "remove it" 😅)

> Do you want the gplus parameter removed from the json

So, I'll default to @gerbrent on this one, but it probably doesn't hurt to just remove all the references to it for all the people.

I will say, we actually just removed all the JSON files from the `data/` folder,  so if you've cloned the repo in the past make sure to do a `git pull` to ensure you've got the most recent changes. (Because you mentioned JSON files)

> the following files changed?

So, typically I don't touch anything in the `themes/jb/assets/css/libs/` folder, in case someone else is using that library for something. The other file should be fine to modify though 😁

Thanks for picking this one up 🥳🚀

(Also, I'd assign you but just found out I can't based on my permission level 😅, which isn't a problem @gerbrent or someone else will be able to add you soon 😁)

**Comment by harriseldon** [comment]
Thanks. I updated my local repository.
This is the command that I am using to remove the gplus lines from all of the md files.
``` shell
find ./ -type f -name "*.md" -exec fgrep -il "gplus" {} \; | xargs sed -i '/gplus:\s\S*/d'
```
I will manually update the layouts file then create a merge request.

**Comment by harriseldon** [comment]
Here is the explainshell link to the command
https://explainshell.com/explain?cmd=find+.%2F+-type+f+-name+%22*.md%22+-exec+fgrep+-il+%22gplus%22+%7B%7D+%5C%3B+%7C+xargs+sed+-i+%27%2Fgplus%3A%5Cs%5CS*%2Fd%27

Key is the sed expression

/ [starts regex]
gplus: [matches exact starting point in markdown -- could have added ^ to find the start of the line]
\s [white space]
\S* [0 or more non whitespace. This catches null and also the full url]
/d [The d options means to the delete the entry rather than replace. I had to search for this online]

**Comment by gerbrent** [comment]
closing, as this is complete
