### ISSUE TITLE
Adjust PeerTube iframe width on mobile devices

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#278]
The width of the dynamic PeerTube iframe is wider than the device width on mobile devices, so the page scrolls horizontally.

![Screenshot_20220814-154919](https://user-images.githubusercontent.com/35609464/184540398-7bfee6ad-4e46-4e08-b00a-5f4e297ef827.jpg)

![Screenshot_20220814-154930](https://user-images.githubusercontent.com/35609464/184540397-719eae31-ef29-45f2-a41d-ea1fdfc22f0b.jpg)

**Comment by iarwain-forn** [comment]
I was sitting there, thinking to myself "Should I test this on mobile?" apparently the answer was yes 😑 

It's been a long time since I've been doing frontend, @reesericci what would you suggest for making the iframe responsive? I'm not sure if a percentage based width and height would be the best bet or if there's some magic Hugo can do for responsive design.

**Comment by reesericci** [comment]
Change the width and height based on media queries in the CSS - that's the best you can do with iFrames.

**Comment by reesericci** [comment]
But if you just want it to span the entire width - use 100vw for the width and auto height
