### ISSUE TITLE
Hosts and Guest Page: Shows are listed twice

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#320]
On the host page, at the moment, every show is listed twice.

For example, Chris' page:
https://new.jupiterbroadcasting.com/hosts/chris/
![image](https://user-images.githubusercontent.com/35609464/185622811-506f60a2-db38-4a7c-8bef-033978b7192e.png)

The first link links to the show page, the second link to the hosts page (_/hosts_).

The same is true for the guest page.
https://new.jupiterbroadcasting.com/guests/popey/

This seems to be the logic that lists the shows: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/904cd3612b12129c766d9bdf26e8b156f47b679e/themes/jb/layouts/taxonomy/host.html#L21
https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/904cd3612b12129c766d9bdf26e8b156f47b679e/themes/jb/layouts/taxonomy/guest.html#L20

**Comment by elreydetoda** [comment]
...I think I know why this happened...because `/hosts` (off of the show) is just a symlink to the `_index.md` file above it...so they're both match that criteria... :facepalm: 

I'd originally used that because that's how things were getting filtered before, and I couldn't test for that because they were in different commits/branches and they were merged to main separately but in a similar time frame. So, I don't think there was a way to check for that :sweat_smile: 

I'll get this fixed later. :upside_down_face:
