### ISSUE TITLE
deploy after scraping - not deploying despite successful scrape

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#371]
Noticed a behaviour:

There has been a successful "scrape & commit" action on Coder 481 [here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/1e4fac76e1a10a55edcf1f429f3507de69a5e13f) about "17 hours ago"

Great! (despite other unrelated issues  #367 )

This, however, is not being pushed into production at time of scrape, and thus [Coder 481](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/content/show/coder-radio/0481.md) exists in code, but has not been published to jupiterbroadcasting.com. Should be https://www.jupiterbroadcasting.com/show/coder-radio/481/ - currently a 404.

### Questions
* Do I have this right? 
* Is this by design, then, and we just haven't noticed w all the feature PRs being pushed, publishing newly scraped episodes along w PR merges?
* Should we be pushing scraped data on successful scrape?
   * this can be dangerous.. if the scraper misbehaves, we do not want to wipe production data..
   * so, perhaps our new E2E tests can come into play? If tests pass, then publish. If not.... do not.
      * may need to write new tests to specifically target known-good episodes exist..

**Comment by gerbrent** [comment]
I will do a manual deploy to prod via workflow run to publish Coder 481.

**Comment by gerbrent** [comment]
[Deployed](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/runs/2969089729) and Coder 481 now published 👍🏻

**Comment by gerbrent** [comment]
related: #215 #365 #366 #367 (possible duplicate)

**Comment by elreydetoda** [comment]
> Should we be pushing scraped data on successful scrape?

IMO, yes we should.

> this can be dangerous.. if the scraper misbehaves, we do not want to wipe production data..

in theory there shouldn't be that much to worry about, because it could easily be disabled via the web-ui and someone can revert the commit. Since the bot isn't doing a force push, which could erase history, it should then trigger a re-deploy after the commit being reverted.

If we had a versioned artifact to pull from (summarized [here](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/307#issuecomment-1234139769)), then this would be an even less concerning situation (I never got feedback though on if we should proceed with that or not though :sweat_smile:).

> * so, perhaps our new E2E tests can come into play? If tests pass, then publish. If not.... do not.
>   * may need to write new tests to specifically target known-good episodes exist..

I've never used this before, but after a quick DDG search I found this: https://github.com/marketplace/actions/pr-automerge-bot

Maybe we could tweak that to handle auto-merging the PRs for the bot? It'd seem like we also have to do that for other PRs too though, but maybe not (haven't dug into the setting much).

If we did need to do it for other PRs we could tag people based on file paths with this: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by ChrisLAS** [comment]
Linux Action News 265 has not made it to the new site yet.

https://linuxactionnews.com/256

**Comment by elreydetoda** [comment]
Hey @ChrisLAS , till #366 is merged someone will have to navigate to here: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/workflows/deploy-prod.yml and push the "Run workflow" button.

![image](https://user-images.githubusercontent.com/10230166/188210075-afba21c8-a0fb-4d5b-9504-9b0b80fbbc57.png)

Alternatively I've got a curl command here: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/215#issuecomment-1204742444

You'll just need to generate a PAT (Personal Access Token) via GH's web-ui, which I link to in that comment and showed a screenshot of the permissions I assigned it.

This will only have to happen when the scraper picks up new episodes (which aren't necessarily instant, unless castablasta integration is made like mentioned [here[(https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/215#issuecomment-1204743745))

**Comment by gerbrent** [comment]
Merging this functionality in #366 to be solved more elegantly with CastaBlasta publishing pipeline in the future.
