### ISSUE TITLE
Contact form covered by footer

### ISSUE THREAD

**Issue by zethra** [JupiterBroadcasting/jupiterbroadcasting.com#437]
### URL

https://www.jupiterbroadcasting.com/contact/

### On what type of device(s) did you see this bug?

Phone

### On which browser(s) are you seeing the problem?

Firefox

### Summary

If you submit the contect form without filling out all the feilds it shows an error. On mobile, the causes the bottom on the form, including the submit button to be covered by the footer.

![Screenshot_20220930-183539](https://user-images.githubusercontent.com/6034238/193365493-f20d38bc-e101-4268-9f09-ee25b8454b41.png)

### Contributing

- [x] I have read through the [Contributing Guidelines](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/main/CONTRIBUTING.md)

**Comment by elreydetoda** [comment]
Nice find @zethra !

Definitely something we should also create a test case for, once we figure out how to fix this, so we can make sure it doesn't happen again.

**Comment by CGBassPlayer** [comment]
This also happens on the desktop if no data is filled out
![image](https://user-images.githubusercontent.com/34293941/194211192-03600d31-b2f1-4609-82fa-1fc2818a9d98.png)

This is due to the `iframe` that the contact page lives on being locked at 780px. and the errors making the content on the Wufoo form larger than that. I can look into this.
```html
<iframe height="780" allowTransparency="true" frameborder="0" scrolling="no" style="width:100%;border:none"  src="https://jblive.wufoo.com/embed/w7x2r7/"><a href="https://jblive.wufoo.com/forms/w7x2r7/">Fill out my Wufoo form!</a></iframe>
```
This one will be hard to test because playwright can still click a button it cannot see if I remember correctly. I will leave the link to the docs relating to this here as well
https://playwright.dev/python/docs/api/class-framelocator

**Comment by gerbrent** [comment]
thanks for finding/reporting this @zethra , and thanks for tackling it @CGBassPlayer - 🎉
