### ISSUE TITLE
hugo WARN: no layout file for "webplayer" for kind "page"

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#46]
solve hugo runtime WARN:
> found no layout file for "webplayer" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

**Comment by gerbrent** [comment]
![image](https://user-images.githubusercontent.com/7018928/177740312-c370d376-4a45-482f-833f-788e027292fc.png)

**Comment by StefanS-O** [comment]
I think those should only be generated for kind episode

**Comment by kbondarev** [comment]
I searched around the web for those warning messages and that lead me to the config.toml file and [this hugo doc page about output formats](https://gohugo.io/templates/output-formats/). 

Changing these lines at the bottom of config.toml by deleting bunch of stuff stops the warnings:

> Original:
> ```toml
> [outputFormats]
>   [outputFormats.webplayer]
>   mediatype ="application/json"
>   baseName = "webplayer"
> 
> [outputs]
>   page = ["json","html","webplayer"]
>   section = ["html","rss"]
> ```
> 
> Leave only this:
> ```toml
> [outputs]
>   page = ["html"]
>   section = ["html","rss"]
> ```
> 


@StefanS-O, can help confirm my guessings here:
- The "json" output for `page` would make basically a JSON API for each episode? But it spits the warning since there's no template?
- The "[outputFormats.webplayer]" is a special definiton of an output format for the Podlove player? To consume things like chapters, related episodes, etc? (I think you mentioned something about it before)

**Comment by elreydetoda** [comment]
no more :slightly_smiling_face: 
![image](https://user-images.githubusercontent.com/10230166/185450765-e52b1714-4919-4373-a6a1-ec34c12ed44f.png)
