### ISSUE TITLE
jupiterbroadcasting.net expired SSL Certificate

### ISSUE THREAD

**Issue by TeamLinux01** [JupiterBroadcasting/jupiterbroadcasting.com#476]
### URL

https://jupiterbroadcasting.net

### On what type of device(s) did you see this bug?

Phone, Desktop

### On which browser(s) are you seeing the problem?

Firefox, Chrome, Microsoft Edge

### Other Browser

Vivaldi

### Summary

The SSL certificate for jupiterbroadcasting.net expired on Oct 20, 2022.

**Comment by TeamLinux01** [comment]
May I suggest that the .net site do a redirect to https://jupiterboardcasting.com, that way it doesn't require a certificate at all?

**Comment by CGBassPlayer** [comment]
I've used this URL before the expiration and it did redirect to the jb.com. Not really sure what is happening on the backend for redirecting

**Comment by pagdot** [comment]
> May I suggest that the .net site do a redirect to https://jupiterbroadcasting.com, that way it doesn't require a certificate at all?

It does. At least if you use some kind of HTML or HTTP(S) based forwarding (3.g. [HTTP 301 Moved permanently(https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301)) because you still need to establish a HTTPS connection. Pure HTTP forwarding would be possible, afaik most web browsers prefer HTTPS and may even warn with HTTP

**Comment by gerbrent** [comment]
Adding @stefanso since he is the domain owner..
