### ISSUE TITLE
Consider Plausible - open source website analytics

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#70]
[Plausible: Open source Google Analytics alternative | Plausible Analytics](https://plausible.io/open-source-website-analytics)

First Question: Do we even want/need analytics?

**Comment by ironicbadger** [comment]
This is simple enough to do if you still want it. We already have a plausible instance running it would just be a case of injecting the tracking code into the hugo site headers.

**Comment by gerbrent** [comment]
@elreydetoda - can you help Alex implement the into Hugo-speak?

**Comment by elreydetoda** [comment]
No problem, I can get this implemented after work (17:00 EST).

**Comment by elreydetoda** [comment]
Alright, I think that PR should work. I made it a bit more dynamic so we could potentially use it for other sites (i.e. jb-live (once we merge the footer/menu into that theme), if we have a dev.jb.com, etc.). So, that's why I'm saying it _should_ work :upside_down_face: 

If not we can just pass in the data-domain via the params.toml like how I did for the url.

Also, @ironicbadger is there anyway you could rename the plausible file to something else, because by default the way I getting the file it's keeping the plausible name in the filename. I'm pretty sure I've seen regex before  (IIRC in uBlock origin) just based on the word plausible. So, if you change it to something that uBlock doesn't key off of then you'll probably get more analytics data.

**Comment by ironicbadger** [comment]
Confirmed working! 🥳
