### ISSUE TITLE
hosts listing on Show pages - improve layout

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#87]
The current vertical stacking of multiple hosts seems to be an inefficient use of precious screen real estate.

Propose to stack hosts from left-to-right, until window border is reached, then create a new row as needed.

Not sure how easy this is......

![image](https://user-images.githubusercontent.com/7018928/178381849-1014d57c-3f4e-49ae-9b38-83714730e64c.png)

NOTE: ignore the lack of artwork in the episode thumbnails, already mentioned in another issue.

**Comment by kbondarev** [comment]
Since we use bulma for CSS stuff we should strive to implement things like that with it.

I think in this case  either “tiles” or “levels” should be used. I’m not that familiar with bulma, so not exactly sure what’s the difference there.

https://bulma.io/documentation/layout/

**Comment by CGBassPlayer** [comment]
Checking in to see if anyone has worked on this. I tinkered with it a little bit last night and got a start on this. I ended up using "columns" for the CSS as it seemed pretty straight forward.

![Linux Unplugged screenshot with multiple hosts](https://user-images.githubusercontent.com/34293941/180791819-aafd2961-f9c0-44c1-bc51-dbba56468a89.png)
I put Brent in multiple times to test the wrapping as needed. 

On a slightly related note, I think it would be smart to remove the hosts from the links of the show since the hosts face already takes you to that particular hosts page.

**Comment by harriseldon** [comment]
I created this pull request before I read your comment. It does not address it completely, but it does make it horizontal.
https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/179

**Comment by CGBassPlayer** [comment]
It's all good. Just putting feelers out to see what's being worked on to prevent double work and actually get some experience with Bulma. I see your pull request tackled the links as well which is good too.

**Comment by CGBassPlayer** [comment]
The icons for the links look great! But the hosts list looks a bit crammed on the Jupiter Extras page. Also some show pages the link icons are pretty spaced out. I will take what @harriseldon did and see if we can't polish it up a little bit

**Comment by CGBassPlayer** [comment]
Unless there is something else that we would like done to the host listings, I think this issue can be closed.
