### ISSUE TITLE
Hosts, Guests - implement filtering on listing page

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#92]
Could be useful to present a simple filter on large Hosts, Guest listing pages.

could potentially relate to #26

**Comment by elreydetoda** [comment]
Ya, I don't know if there has been any matrix discussion about this, but with using hugo (or any type of dynamic modification of the website (i.e. filtering people, which'll modify what's being displayed to the user)) you'll have to use JavaScript to do this.

So, if you just want to implement #26 that's normally more straight forward (IMO) if you want to keep things as static as possible.

The other thing you could do (if you only implement search instead of filters), is that you you don't have to load all the hosts/guests at once. We could implement [pagination](https://gohugo.io/templates/pagination/) very easily with: `{{ template "_internal/pagination.html" . }}` ([example](https://github.com/Climate-Refugee-Stories/crs-website/blob/c82f394a620b4631bb43de5ca4433d33a51bb292/layouts/stories/list.html#L16)), & [example website view](https://www.climaterefugeestories.com/stories/)).

That'll help page loading time, and also allow other's to still find people with ease (via #26).

**Comment by elreydetoda** [comment]
Actually found out that pagination [isn't possible](https://discourse.gohugo.io/t/filtering-data-in-json-using-where/35287/2) with the current way we are doing people (everyone being in a json file), because the range we're doing is getting represented as a map of maps... :disappointed: 

![image](https://user-images.githubusercontent.com/10230166/179421154-e4cb4462-ec60-47fe-b24f-eb53db31f7f9.png)


This is even more of a reason we probably should modify the way we're representing people, I'm about to create an issue about this...I was going to try and do it before (when I was more active), but I didn't get a chance to at the time :sweat:

**Comment by kbondarev** [comment]
I think adding a small pure JavaScript script for filtering would be a good solution.

---

> This is even more of a reason we probably should modify the way we're representing people

@elreydetoda, I don't think there anything wrong with the way people are defined and represented right now. 
Any data-structure (map of maps in this case) could be manipulated to become any other structure you require. I'm not entirely sure I understand the problem you described.

**Comment by elreydetoda** [comment]
> @elreydetoda, I don't think there anything wrong with the way people are defined and represented right now. 
> Any data-structure (map of maps in this case) could be manipulated to become any other structure you require. I'm not entirely sure I understand the problem you described, can you please elaborate more?

I'm making an issue for it, and will probably have it finished by tonight (want it to be comprehensive for why I want to change things up), but just got done with a call with a family member and am getting groceries before it gets too late 😅.

So, I'll try and finish it up tonight whenever I get back on again.

**Comment by elreydetoda** [comment]
alright @kbondarev, it's a lengthy one but I'm trying to be as clear as possible as to why I think it's worth migrating to using more hugo native pages instead of json: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/110

**Comment by elreydetoda** [comment]
BTW, pagination was implemented in #144
